### PR TITLE
Allow server settings from config

### PR DESCRIPTION
**Pull request by BrunoBernardino**
This way one can set something like:

```
var fs = require('fs');

var serverOptions = {};

if (process.env.MONGO_SSL_CERT) {
  serverOptions.ssl = true;
  serverOptions.sslCert = fs.readFileSync(process.env.MONGO_SSL_CERT);
  serverOptions.sslKey = fs.readFileSync(process.env.MONGO_SSL_CERT);
  serverOptions.sslCA = fs.readFileSync(process.env.MONGO_SSL_CA);
  if (process.env.MONGO_SSL_PASS) {
    serverOptions.sslPass = process.env.MONGO_SSL_PASS;
  }
  serverOptions.sslValidate = false;
}

module.exports = {
  "development": {
    "host": "localhost",
    "db": "app_development",
    "server": serverOptions
  },
  "production": {
    "host": process.env.MONGO_HOST || 'localhost',
    "db": process.env.MONGO_DB || 'app',
    "port": process.env.MONGO_PORT || 27017,
    "username": process.env.MONGO_USER || null,
    "password": process.env.MONGO_PASS || null,
    "server": serverOptions
  }
};

```

For the default-config, and SSL works!

### CODE REVIEW

**Comment by ian-mcdevitt** [comment]
:+1:

**Comment by dunestech** [comment]
:+1:

**Comment by RodrigoEspinosa** [comment]
Make sense :+1:

**Comment by BrunoBernardino** [comment]
Thanks!

**Pull request merged**
